[programs.localnet]
anchor_vrf_example = "6MLk7G54uHZ7JuzNxpBAVENANrgM9BZ51pKkzGwPYBCE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
# wallet = "~/.config/solana/id.json"
cluster = "https://switchbo-switchbo-6225.devnet.rpcpool.com/f6fb9f02-0777-498b-b8f5-67cbb1fc0d14"
wallet = "secrets/payer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
